export default defineEventHandler(event => {
  const { page } = getQuery(event)
  if (typeof page !== 'string') throw createError('ERROR')
  const n = parseInt(page)
  const news: ICard[] = [
    {
      id: '',
      category: 'category',
      createdAt: 'JULY 28, 2021',
      title: 'A Survey Into More Sustainable Ways to Practice Dental Hygiene',
      image: '',
      link: 'category/dental-health-and-sustainability',
      slug: 'dental-health-and-sustainability',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'JULY 27, 2021',
      title: 'Employee Portraits – Get to Know Ella and Cedric',
      image: '',
      link: 'category/dentures-and-transplants-what-is-covered-by-the-insurance',
      slug: 'dentures-and-transplants-what-is-covered-by-the-insurance',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'JULY 22, 2021',
      title: 'Tooth Enamel: What It Is and How Important It Is to Protect It',
      image: '',
      link: 'category/employee-portraits-get-to-know-ella-and-cedric',
      slug: 'employee-portraits-get-to-know-ella-and-cedric',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'JULY 12, 2021',
      title: '“Is it okay if our intern watches?” Why we value teaching.',
      image: '',
      link: 'category/have-you-had-your-checkup-this-year-stay-on-top',
      slug: 'have-you-had-your-checkup-this-year-stay-on-top',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'JULY 06, 2021',
      title: 'Have you had your checkup this year? Stay on top.',
      image: '',
      link: 'category/is-it-ok-if-our-intern-watches-why-we-value-teaching',
      slug: 'is-it-ok-if-our-intern-watches-why-we-value-teaching',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'JUNE 28, 2021',
      title: 'We Are Going on Vacation – Closed Office During the First Week of July',
      image: '',
      link: 'category/tooth-enamel-what-it-is-and-how-important-it-is-to-protect-it',
      slug: 'tooth-enamel-what-it-is-and-how-important-it-is-to-protect-it',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'JUNE 03, 2021',
      title: 'When You Need a Fixed Denture and not an Implant',
      image: '',
      link: 'category/we-are-going-on-vacation-closed-office-during-the-first-week-of-july',
      slug: 'we-are-going-on-vacation-closed-office-during-the-first-week-of-july',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'MAY 17, 2021',
      title: 'When Children Start Losing Teeth',
      image: '',
      link: 'category/when-children-start-losing-teeth',
      slug: 'when-children-start-losing-teeth',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'MAY 05, 2021',
      title: 'Dentures and Transplants – What Is Covered by the Insurance',
      image: '',
      link: 'category/when-you-need-a-fixed-denture-and-not-an-implant',
      slug: 'when-you-need-a-fixed-denture-and-not-an-implant',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'APRIL 26, 2021',
      title: 'Corona Virus UpcreatedAt: A New Hygiene Concept in Our Clinic',
      image: '',
      link: 'category/corona-virus-update-a-new-hygiene-concept-in-our-clinic',
      slug: 'corona-virus-update-a-new-hygiene-concept-in-our-clinic',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'APRIL 13, 2021',
      title: 'What to Do When a Dental Emergency Occurs',
      image: '',
      link: 'category/what-to-do-when-a-dental-emergency-occurs',
      slug: 'what-to-do-when-a-dental-emergency-occurs',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'APRIL 09, 2021',
      title: 'Electric Toothbrushes: Guide to Find the Right One',
      image: '',
      link: 'category/electric-toothbrushes-guide-to-find-the-right-one',
      slug: 'electric-toothbrushes-guide-to-find-the-right-one',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'MARCH 30, 2021',
      title: 'Taking Care of Your Teeth (for Kids)',
      image: '',
      link: 'category/taking-care-of-your-teeth-for-kids',
      slug: 'taking-care-of-your-teeth-for-kids',
      isPublished: true,
    },
    {
      id: '',
      category: 'category',
      createdAt: 'MARCH 22, 2021',
      title: 'Candid – Our New Teeth Whitening Technology',
      image: '',
      link: 'category/candid-our-new-teeth-whitening-technology',
      slug: 'candid-our-new-teeth-whitening-technology',
      isPublished: true,
    },
  ]

  function sliceNews(): ICard[] {
    const start = (n - 1) * 4
    const end = 4 * n
    return news.slice(start, end)
  }
  const filteredNews = sliceNews()

  return { news: filteredNews, total: news.length }
})
